version: '2'
services:
    web:
      build: .
      command: python -u app.py
      ports:
        - "80:5000"
      volumes:
        - .:/app
      links:
        - db
        - rabbit
      depends_on:
        - db
        - rabbit

    worker:
        build: .
        command: celery -A tasks worker --loglevel=info
        volumes:
            - .:/app
        links:
            - db
            - rabbit
        depends_on:
            - db
            - rabbit
    db:
      image: mongo
      
    rabbit:
        image: rabbitmq
        ports:
            - "5673:5672"